### ISSUE TITLE
Parse # in the URLs

### ISSUE THREAD

**Issue by navidshaikh** [raviqqe/linkcheck#33]
URLs with `#` returns 400

```
$ liche docs/README.md 
docs/README.md
	ERROR	https://docs.openshift.com/container-platform/4.1/cli_reference/administrator-cli-commands.html#create-kubeconfig
		Bad Request (HTTP error 400)
```

**Comment by chizhg** [comment]
The root cause for this issue is `fasthttp` is not handling URL hash correctly.
Filed https://github.com/valyala/fasthttp/issues/748.

**Comment by erikdubbelboer** [comment]
This has just been fixed in fasthttp in https://github.com/valyala/fasthttp/commit/76b74e34c20dfaf25e491571044655e3fdf39c19
