### ISSUE TITLE
mode of operation for relative links needed

### ISSUE THREAD

**Issue by paul-hammant** [raviqqe/linkcheck#4]
Re `![](/images/foo.png)`

It could be that that image is available locally in `../images/`  (Jekyll is laid out like this with posts in `_posts/`).

Re `![](../another_image_root/foo.png)`

It could be that that image is relatively available online, say "http://some.site/another_image_root" and not at all in the clone/checkout (as the Jekyll case above)

**Comment by raviqqe** [comment]
Thank you for contribution! I committed relative paths support just now.

**Comment by paul-hammant** [comment]
Speedy work, Sir!
