### ISSUE TITLE
Provide a way to exclude links

### ISSUE THREAD

**Issue by raipc** [raviqqe/linkcheck#7]
Thank you for a great tool!
Could you please provide a way to exclude links from checking by providing a list of patterns, e.g. --exclude=localhost,EXAMPLE_DOMAIN*, or using a config file?

**Comment by raviqqe** [comment]
How about regex patterns of URLs? BTW, are you talking about this project
 or [`muffet`](https://GitHub.com/raviqqe/muffet)?

**Comment by raipc** [comment]
Regex patterns would be OK.

I was talking about this project. We are experimenting on analysis of markdown documentation and articles changing before accepting pull requests (spell-checking, link availability checking). Exposing such parameters as concurrency, timeout and ignored patterns should simplify the process a lot.

**Comment by raviqqe** [comment]
Closed by #8.
